---
name: CI_MANUAL

on: workflow_dispatch

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: voxpupuli/gha-puppet/.github/workflows/beaker.yml@v1
    with:
      pidfile_workaround: 'false'
      rubocop: false
      cache-version: '1'
